spring:
  application:
    name: recyce-eureka-service-ha
  profiles:
    active: peer3
server:
  port: 8763
#因为当前的eureka是单机版，需要配置
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://westar:recycle@peer2:8762/eureka,http://westar:recycle@peer1:8761/eureka
security:
  basic:
    enabled: true #开启安全配置，只能放在application.yml中
  user:
    name: westar
    password: recycle