server:
  port: 9000
#因为当前的eureka是单机版，需要配置
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://westar:recycle@${eureka.instance.hostname}:${server.port}/eureka

security:
  basic:
    enabled: true #开启安全配置，只能放在application.yml中
  user:
    name: westar
    password: recycle